---

###
### Bootstrap System
###
- hosts: all
  roles:
    - apt_repo_meta
  tags:
    - bootstrap-system
    - bootstrap-system-apt-repo

- hosts: all
  vars:
    apt_packages:
      - apt-utils
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
  roles:
    - apt_meta
  tags:
    - bootstrap-system
    - bootstrap-system-apt


###
### Pythonstrap System
###
- hosts: all
  roles:
    - python_meta
  tags:
    - bootstrap-python


###
### Install Role Packages
###

- hosts: all
  roles: [tuning]
  tags: tuning

- hosts: all
  roles: [atom]
  tags: atom

- hosts: all
  roles: [clipmenu]
  tags: clipmenu

- hosts: all
  roles: [diff_highlight]
  tags: diff_highlight

- hosts: all
  roles: [docker]
  tags: docker

- hosts: all
  roles: [docker_compose]
  tags: docker_compose

- hosts: all
  roles: [firefox]
  tags: firefox

- hosts: all
  roles: [fzf]
  tags: fzf

- hosts: all
  roles: [kops]
  tags: kops

- hosts: all
  roles: [kubectl]
  tags: kubectl

- hosts: all
  roles: [neovim]
  tags: neovim

- hosts: all
  roles: [oh_my_zsh]
  tags: oh_my_zsh

- hosts: all
  roles: [sway]
  tags: sway

- hosts: all
  roles: [terraform]
  tags: terraform

- hosts: all
  roles: [zathura]
  tags: zathura


###
### Install fonts
###
- hosts: all
  roles: [font_droid_sans_mono]
  tags:
    - font_droid_sans_mono
    - font
    - fonts

- hosts: all
  roles: [font_font_awesome]
  tags:
    - font_font_awesome
    - font
    - fonts

- hosts: all
  roles: [font_san_francisco]
  tags:
    - font_san_francisco
    - font
    - fonts

- hosts: all
  roles: [font_terminus]
  tags:
    - font_terminus
    - font
    - fonts

###
### Install themes/icons
###
- hosts: all
  roles: [icon_moka]
  tags:
    - icon_moka
    - icon
    - icons

- hosts: all
  roles: [theme_arc]
  tags:
    - theme_arc
    - theme
    - themes


###
### Install Custom apt Packages
###
- hosts: all
  roles:
    - apt_meta
  tags:
    - apt


###
### Set default applications
###
- hosts: all
  roles:
    - xdg_mime_meta
  tags:
    - xdg
    - xdg-open
    - xdg-mime


###
### Manager systemd services
###
- hosts: all
  roles:
    - systemd_meta
  tags:
    - systemd
