---

- name: set bash as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/bash
  become: True

- name: ensure requirements are removed
  include_role:
    name: apt_meta
  vars:
    apt_state: absent
    apt_packages: "{{ oh_my_zsh_shared_packages }}"

- name: remove zshrc and oh-my-zsh base path
  file: path=/{{ ansible_user_id }}/.oh-my-zsh state=absent
  become: True

- name: remove .zshrc
  file: path=/{{ ansible_user_id }}/.zshrc state=absent
  become: True

- name: remove oh-my-zsh-history file
  file: path=/{{ ansible_user_id }}/.zsh_history state=absent
  become: True
