---

- name: add custom motd
  copy:
    src: 05-hostname
    dest: /etc/update-motd.d/05-hostname
    mode: 0755
    owner: root
    group: root
  become: True

- name: edit Bash prompt
  lineinfile:
    dest: /home/{{ ansible_user_id }}/.bashrc
    line: 'export PS1="\[\e[31m\]x\[\e[m\]:\[\e[34m\]\w\[\e[m\]\[\e[37m\]\\$\[\e[m\] "'
    owner: "{{ ansible_user_id }}"

- name: ensure kitty config directory exists
  file:
    path: ~/.config/kitty
    state: directory
    mode: 0755
  register: kitty_conf_dir

- name: create kitty.conf
  file:
    path: "~/.config/kitty/kitty.conf"
    state: touch
  register: kitty_conf
  when: kitty_conf_dir.changed

- name: populate kitty.conf
  lineinfile:
    path: ~/.config/kitty/kitty.conf
    line: "{{ item }}"
    state: present
  when: kitty_conf is succeeded
  with_items:
    - "background_opacity 0.77"
    - "dim_opacity 0.77"
    - "window_margin_width 7"
    - "adjust_line_height 3"
