---

# Enable everything and fail if the service does not exist
- name: ensure systemd services are enabled and started
  include_tasks: systemd.yml
  vars:
    systemd_item_name: "{{ item }}"
    systemd_item_state: started
    systemd_item_enabled: True
    systemd_item_masked: False
  register: systemd_service_deployed
  with_items:
    - "{{ systemd_enabled }}"

# Disable and mask everything, but do not fail if the
# service does not exist
- name: ensure systemd services are stopped and maksed
  include_tasks: systemd.yml
  vars:
    systemd_item_name: "{{ item }}"
    systemd_item_state: stopped
    systemd_item_enabled: False
    systemd_item_masked: True
  with_items:
    - "{{ systemd_disabled }}"
