---

- name: pull service facts
  service_facts:

- name: "check if systemd service exists: {{ systemd_item_name }}"
  fail:
    msg: "{{ systemd_item_name }}" is not installed
  when: ansible_facts.services["{{ systemd_item_name }}"] is not defined
  changed_when: False
  failed_when: False
  register: systemd_service_available

- name: "ensure systemd service is managed: {{ systemd_item_name }}"
  systemd:
    name: "{{ systemd_item_name }}"
    state: "{{ systemd_item_state }}"
    enabled: "{{ systemd_item_enabled }}"
    masked: "{{ systemd_item_masked }}"
  become: True
  when: systemd_item_fail_on_error == True or systemd_service_available.rc == 0
