---

###
### Custom variables
###
debian_dist: buster



###
### Debian apt repositories
###
apt_repo_repositories:
  # main
  - file: debian-main
    repo: "deb http://deb.debian.org/debian {{ debian_dist }} main contrib non-free"
  - file: debian-main
    repo: "deb-src http://deb.debian.org/debian {{ debian_dist }} main contrib non-free"
  # updates
  - file: debian-updates
    repo: "deb http://deb.debian.org/debian {{ debian_dist }}-updates main contrib non-free"
  - file: debian-updates
    repo: "deb-src http://deb.debian.org/debian {{ debian_dist }}-updates main contrib non-free"
  # security
  - file: debian-security
    repo: "deb http://security.debian.org {{ debian_dist }}/updates main contrib non-free"
  - file: debian-security
    repo: "deb-src http://security.debian.org {{ debian_dist }}/updates main contrib non-free"


###
### Systemd services
###
systemd_enabled: []

# https://github.com/Airblader/dotfiles-manjaro/blob/master/SETUP
systemd_disabled:
  - exim4.service
  - ModemManager.services
  - nfs-common.service
  - rpcbind.service
  - rpcbind.target
  - binfmt-support.service


###
### System Python versions
###
python_3: True


###
### Python pip packages (add your custom packages here)
###
pip2_packages:
  - awscli
  - aws-adfs
  # https://github.com/chrisallenlane/cheat
  - cheat

pip3_packages: []


###
### Debian packages (add your custom packages here)
###
apt_packages:
# ---- Base Utils ----
  - curl
  - direnv
  - dnsutils
  - dolphin
  - figlet
  - gnupg
  - gnupg-agent
  - htop
  - imagemagick
  - iw
  - keychain
  - less
  - lolcat
  - lsb-release
  - lsof
  - man-db
  - manpages
  - mc
  - moreutils
  - net-tools
  - pinentry-tty
  - pwgen
  - socat
  - terminator
  - tmux
  - traceroute
  - tree
  - wget
  - wireless-tools
  - xxd
# ---- Sec Tools (default) ----
  - netcat
  - nmap
  - wireshark-gtk
# ---- Sec Tools (wireless) ----
  - aircrack-ng
  - horst
  - kismet
  - kismet-plugins
# ---- Theme tools ----
#  - qt4-qtconfig
# ---- Fonts ----
  - fontconfig
  - fonts-arphic-ukai
  - fonts-arphic-uming
  - fonts-ipafont-gothic
  - fonts-ipafont-mincho
  - fonts-liberation
  - fonts-open-sans
  - fonts-opensymbol
  - fonts-symbola
  - ttf-mscorefonts-installer
  - ttf-wqy-zenhei
# ---- Firmwares ----
  - intel-microcode
  - firmware-misc-nonfree
  - firmware-linux
  - firmware-iwlwifi
  #- firmware-crystalhd (not available in debian buster)
# ---- Block devices ----
  - libblockdev-plugins-all
  - udisks2-btrfs
  - udisks2-lvm2
# ---- Window Manager ----
# ---- Office / Productivity ----
  - keepassx
# ---- Video ----
  - vlc
  - vlc-plugin-notify
  - vlc-plugin-samba
  - x264
  - x265
# ---- Audio ----
  - alsa-utils
  - alsa-oss
  - blueman
  - pavucontrol
  - pulseaudio
  - pulseaudio-module-bluetooth
  - pulseaudio-utils
# ---- Network clients ----
  - jxplorer
  - mariadb-client
  - openssh-client
  - redis-tools
  - remmina
  - remmina-plugin-nx
  - remmina-plugin-rdp
  - remmina-plugin-vnc
  - remmina-plugin-xdmcp
  - swaks
# ---- Development ----
  - ack
  - ack-grep
  - binutils
  - devscripts
  - dos2unix
  - exuberant-ctags
  - jq
  - packer
  - pep8
  - php-cli
  - pylint
  - pylint3
  - python-pep8
  - python3-pep8
  - shellcheck
  - silversearcher-ag
  - tig
  - yamllint
# ---- chat ----
  - weechat
# ---- dbus ----
  #- dbus
  #- dbus-user-session
  #- dbus-x11


###
### Select packages to install
###
### 'install': Install the package
### 'remove':  Uninstall the package
### Any other value will ignore the package (neither install nor uninstall)

atom:                  'install'
clipmenu:              'install'
diff_highlight:        'install'
docker:                'install'
docker_compose:        'install'
firefox:               'install'
font_font_awesome:     'install'
font_droid_sans_mono:  'install'
font_san_francisco:    'install'
font_terminus:         'install'
fzf:                   'install'
icon_moka:             'install'
kops:                  'install'
kubectl:               'install'
neovim:                'install'
oh_my_zsh:             'install'
sway:                  'install'
terraform:             'install'
theme_arc:             'install'
tuning:                'install'
zathura:               'install'


###
### Settings for packages
###


# ---- Docker ----
# 'wheezy', 'jessie', 'stretch' or 'buster'
docker_repo_dist: "{{ debian_dist }}"
# 'stable' or 'edge'
docker_repo_channel: stable

# ---- FZF ----
# Add sourcing ~/.fzf.bash to your normal shell config?
fzf_update_rc: True
# Enable/Disable fuzzy completion (bash & zsh)?
fzf_completion: False
# Enable/disable key bindings (CTRL-T, CTRL-R, ALT-C)?
fzf_key_bindings: False


###
### Set your preferred default applications
###
xdg_mime_defaults:
  - desktop_file: dolphin.desktop
    mime_types:
      - inode/directory
  - desktop_file: firefox.desktop
    mime_types:
      - text/html
      - text/xml
      - application/xhtml_xml
      - application/x-mimearchive
      - x-scheme-handler/http
      - x-scheme-handler/https
  - desktop_file: zathura.desktop
    mime_types:
      - application/pdf
      - application/postscript
      - application/eps
      - application/x-eps
      - image/eps
      - image/x-eps
